# Generated by Django 5.2.8 on 2025-11-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_rename_users_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
